#!/usr/bin/env bash

echo "Hello from Plegger!"

# set path for recording
REC_PATH="/home/pi/recordings"

# set ALSA as the recording mode for sox
export AUDIODRIVER=alsa

# set a large input buffer to avoid recording glitches
export SOX_OPTS="--input-buffer 64000"

# tell sox which audio device to use
export AUDIODEV=hw:0

echo "Recording "$(date +"%Y-%m-%d_%H-%M-%S").mp3

while true;
do
rec -r 44100 -C 192 -c 2 $REC_PATH/$(date +"%Y-%m-%d_%H-%M-%S").flac silence 1 0.1 3% 1 3.0 3% && break;
done

echo "I quit!"
