#!/usr/bin/env bash
# sox and libsox-fmt-mp3 are dependencies

# get the path to this script
SCRIPT_PATH=$(readlink -f "$0")

# set path for recording
REC_PATH="/home/pi/recordings"

# set the silence threshold as a percentage
THRESHOLD=1%

# set the duration of sound before recording starts
START_DELAY=0.001

# set the duration of silence before recording ends
END_DELAY=5.0

# set ALSA as the recording mode for sox
export AUDIODRIVER=alsa

# set a large buffer to avoid recording glitches
export SOX_OPTS="--buffer 128000"

# tell sox which ALSA device to use
export AUDIODEV=hw:0

echo "-------------------"
echo "Hello from Plegger Recorder!"

FILE=$REC_PATH/$(date +"%Y-%m-%d_%H-%M-%S")
INPUT_FILE=$FILE.mp3

echo "Recording $INPUT_FILE"
rec -r 44100 -C 192 -c 2 $INPUT_FILE silence 1 $START_DELAY $THRESHOLD 1 $END_DELAY $THRESHOLD || exit 1

echo "I quit!"

# restart the script
exec "$SCRIPT_PATH"
